{
 "title": "Spark HTTP requests",
 "tags": [
  "Elasticsearch",
  "Logstash"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "bucketname",
    "label": "Bucket",
    "query": "dimension_values($region,AWS/S3,BucketSizeBytes,BucketName)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Http requests into Bucket</span>\n</div>"
  },
  { "title": "Cloudwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Get Requests",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Put Requests",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Post Requests",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "PostRequests",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "List Requests",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "ListRequests",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Head Requests",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "description": "The number of bytes downloaded/uploaded that contain a request body, made to an Amazon S3 bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Bytes Downloaded",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Bytes Uploaded",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Time",
   "type": "graph",
   "description": "This parameter displays the elapsed time per request from the first byte received to the last byte sent to a bucket. This includes the time taken to receive the request body and send the response body, which is not included in FirstByteLatency.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Bytes Downloaded",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Bytes Uploaded",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Spark Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Step 1 statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpMethod.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "field": "totalTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "bytesSent",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "objectSize",
       "id": "6",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "key:\"*mme.txt\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Step 2 statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpMethod.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "field": "totalTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "bytesSent",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "objectSize",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "key:\"testsparksource/s3performanceOutput/*\" AND bucketName: netpulse-poc-test",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Step 3 statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpMethod.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "field": "totalTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "bytesSent",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "objectSize",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "key:\"testsparksource/s3performanceOutput2/*\" AND bucketName: netpulse-poc-test",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}