{
 "title": "HBase and Hive",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HBase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Hive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "DB Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "hivemetastore",
     "hosts": "ip-10-7-0-42.example.com",
     "metric": "default.General.init_total_count_dbs",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Table Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "hivemetastore",
     "hosts": "ip-10-7-0-42.example.com",
     "metric": "default.General.init_total_count_tables",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "hivemetastore",
     "hosts": "ip-10-7-0-42.example.com",
     "metric": "default.General.init_total_count_partitions",
     "precision": "default",
     "transform": "none"
    }
   ]
  }
 ]
}