---
## Default Kibana configuration from Kibana base image.
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://localhost:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana
elasticsearch.password: ilovekibana
#xpack.security.encryptionKey: "foo_fighters"
xpack.security.session.idleTimeout: "10m"


