---
## Default Kibana configuration from Kibana base image.
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "https://es01:9200","https://es02:9200","https://es03:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: PleaseChangeMe
#xpack.security.encryptionKey: "foo_fighters"
xpack.security.session.idleTimeout: "10m"


