---
## Default Kibana configuration from Kibana base image.
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "https://es01:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana
elasticsearch.password: ilovekibana
xpack.security.encryptionKey: "PhtvIdibB2CWOq0TaglAWKQvC4FUl0rT"
xpack.security.session.idleTimeout: "10m"


