{
 "title": "Amazon S3",
 "tags": [
  "AWS",
  "Amazon",
  "Cloudwatch",
  "S3"
 ],
 "time": { "from": "2020-01-03T15:58:31.359Z", "to": "2020-01-03T16:56:58.735Z" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "bucketname",
    "label": "BucketName",
    "query": "dimension_values($region,AWS/S3,BucketSizeBytes,BucketName)"
   }
  ]
 },
 "panels": [
  { "title": "Bucket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bucket Size Bytes (Daily)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "BucketName": "$bucketname", "StorageType": "StandardStorage" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Number of Objects (Number)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "BucketName": "$bucketname", "StorageType": "AllStorageTypes" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
       "metricName": "AllRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Get Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
       "metricName": "GetRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Put Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
       "metricName": "PutRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Delete Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
       "metricName": "DeleteRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Head Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
       "metricName": "HeadRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Post Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname" },
       "metricName": "PostRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "List Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of Requests",
       "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
       "metricName": "ListRequests",
       "namespace": "AWS/S3",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  { "title": "Bytes Download/Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bytes Downloaded Sum",
   "type": "graph",
   "description": "The number of bytes downloaded for requests made to an Amazon S3 bucket, where the response includes a body.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "bucket 3 poc",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "ref netpulse",
     "dimensions": { "BucketName": "ref-netpulse-poc", "FilterId": "EntireBucket" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "region": "eu-west-2",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Bytes Uploaded Sum",
   "type": "graph",
   "description": "The number of bytes uploaded that contain a request body, made to an Amazon S3 bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "BucketName": "ref-netpulse-poc", "FilterId": "EntireBucket" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "region": "eu-west-2",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "FirtsByteLatency",
   "type": "graph",
   "description": "The per-request time from the complete request being received by an Amazon S3 bucket to when the response starts to be returned.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "ref",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "bucket 3 poc",
     "dimensions": { "BucketName": "bucket-3-poc-netpulse", "FilterId": "EntireBucket" },
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Total Request Latency",
   "type": "graph",
   "description": "The elapsed per-request time from the first byte received to the last byte sent to an Amazon S3 bucket. This includes the time taken to receive the request body and send the response body, which is not included in FirstByteLatency.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "ref",
     "dimensions": { "BucketName": "$bucketname", "FilterId": "EntireBucket" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "bucket 3 poc",
     "dimensions": { "BucketName": "bucket-3-poc-netpulse", "FilterId": "EntireBucket" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}