{
 "title": "Amazon EC2",
 "tags": [
  "AWS",
  "Amazon",
  "Cloudwatch",
  "EC2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instancename",
    "label": "Tag Name",
    "query": "ec2_instance_attribute(eu-west-1, Tags.Name, {})"
   },
   {
    "name": "instanceid",
    "label": "Instance ID",
    "query": "ec2_instance_attribute(eu-west-1, InstanceId, {\"tag:Name\": [\"$instancename\"]})"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Bastion",
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Disk Read/Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Average Disk Read Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "DiskReadOps",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Average Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Average Disk Write Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "metricName": "DiskWriteOps", "namespace": "AWS/EC2", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Network In",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceid" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}